title: Luis Likes Math
description: A blog about math, machine learning, and education

url: http://luisguiserrano.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Articles
   url: /articles
 - title: Videos
   url: /tutorials
 - title: Research
   url: /research
 - title: Talks
   url: /talks
 - title: About
   url: /about

social:
   github: luisguiserrano
   twitter: luis_likes_math
   facebook: luisguiserrano
   email: luisguiserrano@gmail.com

google_analytics: "UA-105245548-1"
