# Site settings
title: Luis Serrano, PhD
description: 'Educator, Mathematician, and Machine Learning Professional'
url: 'https://luisguiserrano.github.io'
baseurl: '/'
disqus_shortname: 'luisguiserrano-github-io'

author:
  name: 'Luis Serrano'
  email: luisguiserrano@gmail.com
  twitter_username: luis_likes_math
  facebook_username: luisguiserrano
  github_username:  luisguiserrano
  linkedin_username:  luisgserrano

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
theme:minima
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
