title: Luis Likes Math
description: A blog about math, machine learning, and education

url: http://luisguiserrano.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html

social:
   github: luisguiserrano
   twitter: luis_likes_math
   facebook: luisguiserrano
   email: luisguiserrano@gmail.com

google_analytics: "UA-105245548-1"
